[package]
name = "metrics"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.2"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
sysinfo = "0.29"
anyhow = "1.0"