[package]
name = "pi5-sha-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
rand = "0.8"
hex = "0.4"

sha1 = { version = "0.10", default-features = true }
sha2 = { version = "0.10", default-features = true }

[features]
default = []
accel = ["sha1/asm", "sha2/asm"]
