[package]
name = "sha_bench"
version = "0.1.0"
edition = "2021"

[lib]
name = "sha_bench"
path = "src/lib.rs"

[dependencies]
rand = "0.8"
sha1 = "0.10"
sha2 = "0.10"

[features]
# No default acceleration so we can produce truly different builds
default = []
soft = []
# Enable ARMv8 SHA1/SHA2 assembly in RustCrypto crates
accel = ["sha1/asm", "sha2/asm"]

# Each binary only builds when its feature is enabled
[[bin]]
name = "soft"
path = "src/bin/soft.rs"
required-features = ["soft"]

[[bin]]
name = "accel"
path = "src/bin/accel.rs"
required-features = ["accel"]
