[package]
name = "sha_bench"
version = "0.1.0"
edition = "2021"

[lib]
name = "sha_bench"
path = "src/lib.rs"

[dependencies]
rand = "0.8"
sha1 = "0.10"
sha2 = "0.10"

[features]
accel = []

[target.'cfg(target_arch = "aarch64")'.dependencies]
sha1 = { version = "0.10", features = ["asm"] }
sha2 = { version = "0.10", features = ["asm"] }

[[bin]]
name = "soft"
path = "src/bin/soft.rs"

[[bin]]
name = "accel"
path = "src/bin/accel.rs"
