[package]
name = "keying"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
getrandom = "0.2"
hkdf = "0.12"
sha2 = "0.10"
p256 = { version = "0.13", features = ["ecdh"] }
rsa = { version = "0.9", features = ["sha2"] }
secrecy = "0.8"