[package]
name = "metrics"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.2"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
sysinfo = "0.29"
anyhow = "1.0"

[dev-dependencies]
tempfile = "3"
